version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

aliases:
  - &node_image cimg/node:16.19.1
  # - &npm_global_cache dependency-cache-v4-{{ checksum ".node-version" }}-{{ checksum "package-lock.json" }}

jobs:
  setup:
    docker:
      - image: *node_image
    steps:
      - checkout
      - sixrs-gke/setup-private-npm
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - ./node_modules
  build:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Build
          command: npm run only:build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  lint:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          environment:
            ESLINT_OPTS: "--format junit --output-file ./reports/eslint/results.xml"
          command: npm run lint
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  test:
    docker:
      - image: *node_image
        environment:
          MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
      - image: gcr.io/plasma-column-128721/mmmbbb:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
        environment:
          # specifying this as test will make it default to a SQLite database
          NODE_ENV: test
          LOG_LEVEL: debug
          PORT: 8801
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run only:test
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Setup NPM auth token
          command: npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      - run:
          name: Publish
          command: ./scripts/release.sh
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup:
          context: 6rs-circle
      - build:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - test:
          context: 6rs-circle
          requires:
            - setup
            - build
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - main
